### ISSUE TITLE
Ocultar órdenes canceladas (por defecto)

### ISSUE THREAD

**Issue by emmafauria** [PaulTOliver/fauria_rentacar#3]
Paul tenemos que generar los reportes sin las ordenes canceladas. (con opcion a poder verlas).

**Comment by PaulTOliver** [comment]
@emmafauria Esto ya esta listo. Por defecto los reportes solo muestran órdenes confirmadas. Aquellas que estén pendientes o canceladas se muestran al clicar los checkbox.

![Screenshot from 2019-03-31 18-47-54](https://user-images.githubusercontent.com/7141288/55292922-9ba44000-53f0-11e9-9bba-80993d2c691f.png)
