### ISSUE TITLE
Añadir Fianza en el contrato (cantidad y forma de pago)

### ISSUE THREAD

**Issue by emmafauria** [PaulTOliver/fauria_rentacar#4]
Buenos días!
Tenermos que poder añadir Fianza en el contrato. 

DOS CAMPOS NUEVOS :
UN PARA AÑADIR CANTIDAD: EJ: 200€
i LA OTRA AÑADIR FORMA DE PAGO DE LA FIANZA: EJ. Efectivo/ Cargo Tarjeta/ Identificacion /Preautorizacion

**Comment by PaulTOliver** [comment]
Fianza listo! :smile: 

![Screenshot from 2019-04-03 20-40-15](https://user-images.githubusercontent.com/7141288/55504545-5e8ab880-5651-11e9-92a5-4a842764f461.png)
